version: '3.8'

services:
  cms:
    build: .
    container_name: cms-visual
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./uploads:/var/www/html/uploads
      - ./data.json:/var/www/html/data.json
      - ./mensajes.json:/var/www/html/mensajes.json
      - ./logs:/var/log/apache2
    environment:
      - ENVIRONMENT=production
      - PHP_MEMORY_LIMIT=256M
      - UPLOAD_MAX_FILESIZE=50M
    restart: unless-stopped
    networks:
      - cms-network

  # Opcional: Servicio de backup automático
  backup:
    image: alpine:latest
    container_name: cms-backup
    volumes:
      - ./uploads:/data/uploads:ro
      - ./data.json:/data/data.json:ro
      - ./mensajes.json:/data/mensajes.json:ro
      - ./backups:/backups
    command: |
      sh -c "
      while true; do
        echo 'Creating backup...'
        tar -czf /backups/backup-$$(date +%Y%m%d-%H%M%S).tar.gz -C /data .
        find /backups -name '*.tar.gz' -mtime +7 -delete
        sleep 86400
      done
      "
    restart: unless-stopped
    networks:
      - cms-network

  # Opcional: Nginx reverse proxy para SSL
  nginx:
    image: nginx:alpine
    container_name: cms-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/ssl/certs:ro
    depends_on:
      - cms
    restart: unless-stopped
    networks:
      - cms-network
    profiles:
      - nginx

networks:
  cms-network:
    driver: bridge

volumes:
  uploads:
  backups: